// <auto-generated />
using System;
using EbayPlatform.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EbayPlatform.Infrastructure.Migrations
{
    [DbContext(typeof(EbayPlatformDbContext))]
    [Migration("20211105100203_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EbayPlatform.Domain.AggregateModel.Accounts.Account", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("主键Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("账单 ID");

                    b.Property<string>("AccountState")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasComment("账单状态");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasComment("币种");

                    b.Property<string>("ShopName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("店铺编号，来自ERP");

                    b.Property<DateTime>("SyncDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getDate()")
                        .HasComment("同步日期");

                    b.HasKey("Id");

                    b.ToTable("Account");

                    b
                        .HasComment("账单");
                });

            modelBuilder.Entity("EbayPlatform.Domain.AggregateModel.Listing.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("主键Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Country")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<long>("HitCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<string>("HitCounter")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("InventoryTrackingMethod")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ItemID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("eBay下载的产品ID、唯一");

                    b.Property<bool>("ItemRevised")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ListingSubType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ListingType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Location")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MSKU")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("渠道SKU");

                    b.Property<string>("PaymentMethods")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("PrivateListing")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasComment("数量");

                    b.Property<string>("QuantityAvailableHint")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("QuantityThreshold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("ShopName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("店铺编号，来自ERP");

                    b.Property<string>("SiteCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("站点");

                    b.Property<DateTime>("SyncDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getDate()")
                        .HasComment("同步日期");

                    b.Property<string>("Title")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b
                        .HasComment("产品");
                });

            modelBuilder.Entity("EbayPlatform.Domain.AggregateModel.Orders.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("主键Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("订单创建日期");

                    b.Property<string>("OrderID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("eBay下载的订单ID、唯一");

                    b.Property<string>("OrderStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("订单状态");

                    b.Property<string>("PaymentMethods")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasComment("付款方式");

                    b.Property<string>("SellerEmail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("卖家邮箱地址");

                    b.Property<string>("SellerUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShopName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("店铺编号，来自ERP");

                    b.Property<DateTime>("SyncDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getDate()")
                        .HasComment("同步日期");

                    b.HasKey("Id");

                    b.ToTable("Order");

                    b
                        .HasComment("订单");
                });

            modelBuilder.Entity("EbayPlatform.Domain.AggregateModel.SyncTaskJobConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("主键Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getDate()")
                        .HasComment("创建日期");

                    b.Property<string>("Cron")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Cron");

                    b.Property<string>("CronDesc")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasComment("Cron描述");

                    b.Property<bool>("Enable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("JobAssemblyName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasComment("程序集名称");

                    b.Property<string>("JobDesc")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Job描述");

                    b.Property<string>("JobName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Job名称");

                    b.Property<int>("JobStatus")
                        .HasColumnType("int")
                        .HasComment("运行状态");

                    b.Property<DateTime?>("ModifyDate")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2")
                        .HasComment("更新日期");

                    b.Property<bool>("SyncErp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.ToTable("SyncTaskJobConfig");

                    b
                        .HasComment("同步任务作业配置");
                });

            modelBuilder.Entity("EbayPlatform.Domain.AggregateModel.SystemLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("主键Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasComment("内容");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getDate()")
                        .HasComment("创建日期");

                    b.Property<string>("LogType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("日志类型");

                    b.Property<string>("ObjectId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("外键Id");

                    b.HasKey("Id");

                    b.ToTable("SystemLog");

                    b
                        .HasComment("系统日志表");
                });

            modelBuilder.Entity("EbayPlatform.Domain.AggregateModel.Accounts.Account", b =>
                {
                    b.OwnsMany("EbayPlatform.Domain.AggregateModel.Accounts.AccountDetail", "AccountDetails", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasComment("主键Id")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<long>("AccountId")
                                .HasColumnType("bigint");

                            b1.Property<string>("AccountType")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<DateTime>("Date")
                                .HasColumnType("Date");

                            b1.Property<string>("Description")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ItemID")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("OrderLineItemID")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<bool>("ReceivedTopRatedDiscount")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bit")
                                .HasDefaultValue(false);

                            b1.Property<string>("RefNumber")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("Title")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("TransactionID")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<decimal>("VATPercent")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)");

                            b1.HasKey("Id");

                            b1.HasIndex("AccountId");

                            b1.HasIndex("RefNumber", "ItemID", "Date", "AccountType");

                            b1.ToTable("AccountDetail");

                            b1.WithOwner()
                                .HasForeignKey("AccountId");

                            b1.OwnsOne("EbayPlatform.Domain.AggregateModel.MoneyValue", "Balance", b2 =>
                                {
                                    b2.Property<long>("AccountDetailId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("bigint")
                                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                                    b2.Property<string>("Currency")
                                        .HasMaxLength(10)
                                        .HasColumnType("nvarchar(10)")
                                        .HasColumnName("BalanceCurrency");

                                    b2.Property<decimal>("Value")
                                        .HasPrecision(18, 3)
                                        .HasColumnType("decimal(18,3)")
                                        .HasColumnName("Balance");

                                    b2.HasKey("AccountDetailId");

                                    b2.ToTable("AccountDetail");

                                    b2.WithOwner()
                                        .HasForeignKey("AccountDetailId");
                                });

                            b1.OwnsOne("EbayPlatform.Domain.AggregateModel.MoneyValue", "ConversionRate", b2 =>
                                {
                                    b2.Property<long>("AccountDetailId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("bigint")
                                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                                    b2.Property<string>("Currency")
                                        .HasMaxLength(10)
                                        .HasColumnType("nvarchar(10)")
                                        .HasColumnName("ConversionRateCurrency");

                                    b2.Property<decimal>("Value")
                                        .HasPrecision(18, 3)
                                        .HasColumnType("decimal(18,3)")
                                        .HasColumnName("ConversionRate");

                                    b2.HasKey("AccountDetailId");

                                    b2.ToTable("AccountDetail");

                                    b2.WithOwner()
                                        .HasForeignKey("AccountDetailId");
                                });

                            b1.OwnsOne("EbayPlatform.Domain.AggregateModel.MoneyValue", "GrossDetailAmount", b2 =>
                                {
                                    b2.Property<long>("AccountDetailId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("bigint")
                                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                                    b2.Property<string>("Currency")
                                        .HasMaxLength(10)
                                        .HasColumnType("nvarchar(10)")
                                        .HasColumnName("GrossDetailAmountCurrency");

                                    b2.Property<decimal>("Value")
                                        .HasPrecision(18, 3)
                                        .HasColumnType("decimal(18,3)")
                                        .HasColumnName("GrossDetailAmount");

                                    b2.HasKey("AccountDetailId");

                                    b2.ToTable("AccountDetail");

                                    b2.WithOwner()
                                        .HasForeignKey("AccountDetailId");
                                });

                            b1.OwnsOne("EbayPlatform.Domain.AggregateModel.MoneyValue", "NetDetailAmount", b2 =>
                                {
                                    b2.Property<long>("AccountDetailId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("bigint")
                                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                                    b2.Property<string>("Currency")
                                        .HasMaxLength(10)
                                        .HasColumnType("nvarchar(10)")
                                        .HasColumnName("NetDetailAmountCurrency");

                                    b2.Property<decimal>("Value")
                                        .HasPrecision(18, 3)
                                        .HasColumnType("decimal(18,3)")
                                        .HasColumnName("NetDetailAmount");

                                    b2.HasKey("AccountDetailId");

                                    b2.ToTable("AccountDetail");

                                    b2.WithOwner()
                                        .HasForeignKey("AccountDetailId");
                                });

                            b1.Navigation("Balance");

                            b1.Navigation("ConversionRate");

                            b1.Navigation("GrossDetailAmount");

                            b1.Navigation("NetDetailAmount");
                        });

                    b.OwnsOne("EbayPlatform.Domain.AggregateModel.Accounts.AdditionalAccount", "AdditionalAccount", b1 =>
                        {
                            b1.Property<long>("AccountId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("AccountCode")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasComment("账户编号");

                            b1.Property<string>("CurrencyCode")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasComment("币种");

                            b1.HasKey("AccountId");

                            b1.ToTable("Account");

                            b1.WithOwner()
                                .HasForeignKey("AccountId");

                            b1.OwnsOne("EbayPlatform.Domain.AggregateModel.MoneyValue", "Balance", b2 =>
                                {
                                    b2.Property<long>("AdditionalAccountAccountId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("bigint")
                                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                                    b2.Property<string>("Currency")
                                        .HasMaxLength(10)
                                        .HasColumnType("nvarchar(10)")
                                        .HasColumnName("BalanceCurrency");

                                    b2.Property<decimal>("Value")
                                        .HasPrecision(18, 3)
                                        .HasColumnType("decimal(18,3)")
                                        .HasColumnName("Balance");

                                    b2.HasKey("AdditionalAccountAccountId");

                                    b2.ToTable("Account");

                                    b2.WithOwner()
                                        .HasForeignKey("AdditionalAccountAccountId");
                                });

                            b1.Navigation("Balance");
                        });

                    b.OwnsOne("EbayPlatform.Domain.AggregateModel.MoneyValue", "InvoiceCredit", b1 =>
                        {
                            b1.Property<long>("AccountId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Currency")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("InvoiceCreditCurrency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)")
                                .HasColumnName("InvoiceCredit");

                            b1.HasKey("AccountId");

                            b1.ToTable("Account");

                            b1.WithOwner()
                                .HasForeignKey("AccountId");
                        });

                    b.OwnsOne("EbayPlatform.Domain.AggregateModel.MoneyValue", "InvoiceNewFee", b1 =>
                        {
                            b1.Property<long>("AccountId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Currency")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("InvoiceNewFeeCurrency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)")
                                .HasColumnName("InvoiceNewFee");

                            b1.HasKey("AccountId");

                            b1.ToTable("Account");

                            b1.WithOwner()
                                .HasForeignKey("AccountId");
                        });

                    b.OwnsOne("EbayPlatform.Domain.AggregateModel.MoneyValue", "InvoicePayment", b1 =>
                        {
                            b1.Property<long>("AccountId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Currency")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("InvoicePaymentCurrency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)")
                                .HasColumnName("InvoicePayment");

                            b1.HasKey("AccountId");

                            b1.ToTable("Account");

                            b1.WithOwner()
                                .HasForeignKey("AccountId");
                        });

                    b.Navigation("AccountDetails");

                    b.Navigation("AdditionalAccount");

                    b.Navigation("InvoiceCredit");

                    b.Navigation("InvoiceNewFee");

                    b.Navigation("InvoicePayment");
                });

            modelBuilder.Entity("EbayPlatform.Domain.AggregateModel.Listing.Product", b =>
                {
                    b.OwnsOne("EbayPlatform.Domain.AggregateModel.Listing.ProductCategory", "FreeAddedCategory", b1 =>
                        {
                            b1.Property<long>("ProductId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("CategoryID")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("FreeAddedCategoryID");

                            b1.Property<string>("CategoryName")
                                .HasMaxLength(300)
                                .HasColumnType("nvarchar(300)")
                                .HasColumnName("FreeAddedCategoryName");

                            b1.HasKey("ProductId");

                            b1.ToTable("Product");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.OwnsOne("EbayPlatform.Domain.AggregateModel.Listing.ProductCategory", "PrimaryCategory", b1 =>
                        {
                            b1.Property<long>("ProductId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("CategoryID")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("PrimaryCategoryID");

                            b1.Property<string>("CategoryName")
                                .HasMaxLength(300)
                                .HasColumnType("nvarchar(300)")
                                .HasColumnName("PrimaryCategoryName");

                            b1.HasKey("ProductId");

                            b1.ToTable("Product");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.OwnsOne("EbayPlatform.Domain.AggregateModel.Listing.ProductCategory", "SecondaryCategory", b1 =>
                        {
                            b1.Property<long>("ProductId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("CategoryID")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("SecondaryCategoryID");

                            b1.Property<string>("CategoryName")
                                .HasMaxLength(300)
                                .HasColumnType("nvarchar(300)")
                                .HasColumnName("SecondaryCategoryName");

                            b1.HasKey("ProductId");

                            b1.ToTable("Product");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.OwnsOne("EbayPlatform.Domain.AggregateModel.Listing.SellingStatus", "SellingStatus", b1 =>
                        {
                            b1.Property<long>("ProductId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<bool>("AdminEnded")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bit")
                                .HasDefaultValue(false);

                            b1.Property<string>("ListingStatus")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<int>("QuantitySold")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasDefaultValue(0);

                            b1.HasKey("ProductId");

                            b1.ToTable("Product");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");

                            b1.OwnsOne("EbayPlatform.Domain.AggregateModel.Listing.PromotionalSaleDetail", "PromotionalSaleDetail", b2 =>
                                {
                                    b2.Property<long>("SellingStatusProductId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("bigint")
                                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                                    b2.Property<DateTime?>("EndTime")
                                        .HasColumnType("datetime2");

                                    b2.Property<DateTime?>("StartTime")
                                        .HasColumnType("datetime2");

                                    b2.HasKey("SellingStatusProductId");

                                    b2.ToTable("Product");

                                    b2.WithOwner()
                                        .HasForeignKey("SellingStatusProductId");

                                    b2.OwnsOne("EbayPlatform.Domain.AggregateModel.MoneyValue", "OriginalPrice", b3 =>
                                        {
                                            b3.Property<long>("PromotionalSaleDetailSellingStatusProductId")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("bigint")
                                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                                            b3.Property<string>("Currency")
                                                .HasMaxLength(10)
                                                .HasColumnType("nvarchar(10)")
                                                .HasColumnName("OriginalPriceCurrency");

                                            b3.Property<decimal>("Value")
                                                .HasPrecision(18, 3)
                                                .HasColumnType("decimal(18,3)")
                                                .HasColumnName("OriginalPrice");

                                            b3.HasKey("PromotionalSaleDetailSellingStatusProductId");

                                            b3.ToTable("Product");

                                            b3.WithOwner()
                                                .HasForeignKey("PromotionalSaleDetailSellingStatusProductId");
                                        });

                                    b2.Navigation("OriginalPrice");
                                });

                            b1.OwnsOne("EbayPlatform.Domain.AggregateModel.MoneyValue", "ConvertedCurrentPrice", b2 =>
                                {
                                    b2.Property<long>("SellingStatusProductId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("bigint")
                                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                                    b2.Property<string>("Currency")
                                        .HasMaxLength(10)
                                        .HasColumnType("nvarchar(10)")
                                        .HasColumnName("ConvertedCurrentPriceCurrency");

                                    b2.Property<decimal>("Value")
                                        .HasPrecision(18, 3)
                                        .HasColumnType("decimal(18,3)")
                                        .HasColumnName("ConvertedCurrentPrice");

                                    b2.HasKey("SellingStatusProductId");

                                    b2.ToTable("Product");

                                    b2.WithOwner()
                                        .HasForeignKey("SellingStatusProductId");
                                });

                            b1.OwnsOne("EbayPlatform.Domain.AggregateModel.MoneyValue", "CurrentPrice", b2 =>
                                {
                                    b2.Property<long>("SellingStatusProductId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("bigint")
                                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                                    b2.Property<string>("Currency")
                                        .HasMaxLength(10)
                                        .HasColumnType("nvarchar(10)")
                                        .HasColumnName("CurrentPriceCurrency");

                                    b2.Property<decimal>("Value")
                                        .HasPrecision(18, 3)
                                        .HasColumnType("decimal(18,3)")
                                        .HasColumnName("CurrentPrice");

                                    b2.HasKey("SellingStatusProductId");

                                    b2.ToTable("Product");

                                    b2.WithOwner()
                                        .HasForeignKey("SellingStatusProductId");
                                });

                            b1.Navigation("ConvertedCurrentPrice");

                            b1.Navigation("CurrentPrice");

                            b1.Navigation("PromotionalSaleDetail");
                        });

                    b.OwnsOne("EbayPlatform.Domain.AggregateModel.MoneyValue", "BuyItNowPrice", b1 =>
                        {
                            b1.Property<long>("ProductId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Currency")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("BuyItNowPriceCurrency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)")
                                .HasColumnName("BuyItNowPrice");

                            b1.HasKey("ProductId");

                            b1.ToTable("Product");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.OwnsOne("EbayPlatform.Domain.AggregateModel.MoneyValue", "BuyerGuaranteePrice", b1 =>
                        {
                            b1.Property<long>("ProductId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Currency")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("BuyerGuaranteePriceCurrency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)")
                                .HasColumnName("BuyerGuaranteePrice");

                            b1.HasKey("ProductId");

                            b1.ToTable("Product");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.OwnsOne("EbayPlatform.Domain.AggregateModel.MoneyValue", "ReservePrice", b1 =>
                        {
                            b1.Property<long>("ProductId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Currency")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("ReservePriceCurrency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)")
                                .HasColumnName("ReservePrice");

                            b1.HasKey("ProductId");

                            b1.ToTable("Product");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.OwnsOne("EbayPlatform.Domain.AggregateModel.MoneyValue", "StartPrice", b1 =>
                        {
                            b1.Property<long>("ProductId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Currency")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("StartPriceCurrency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)")
                                .HasColumnName("StartPrice");

                            b1.HasKey("ProductId");

                            b1.ToTable("Product");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.Navigation("BuyerGuaranteePrice");

                    b.Navigation("BuyItNowPrice");

                    b.Navigation("FreeAddedCategory");

                    b.Navigation("PrimaryCategory");

                    b.Navigation("ReservePrice");

                    b.Navigation("SecondaryCategory");

                    b.Navigation("SellingStatus");

                    b.Navigation("StartPrice");
                });

            modelBuilder.Entity("EbayPlatform.Domain.AggregateModel.Orders.Order", b =>
                {
                    b.OwnsOne("EbayPlatform.Domain.AggregateModel.MoneyValue", "AdjustmentAmount", b1 =>
                        {
                            b1.Property<long>("OrderId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Currency")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("AdjustmentAmountCurrency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)")
                                .HasColumnName("AdjustmentAmount");

                            b1.HasKey("OrderId");

                            b1.ToTable("Order");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.OwnsOne("EbayPlatform.Domain.AggregateModel.MoneyValue", "AmountPaid", b1 =>
                        {
                            b1.Property<long>("OrderId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Currency")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("AmountPaidCurrency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)")
                                .HasColumnName("AmountPaid");

                            b1.HasKey("OrderId");

                            b1.ToTable("Order");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.OwnsOne("EbayPlatform.Domain.AggregateModel.MoneyValue", "AmountSaved", b1 =>
                        {
                            b1.Property<long>("OrderId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Currency")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("AmountSavedCurrency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)")
                                .HasColumnName("AmountSaved");

                            b1.HasKey("OrderId");

                            b1.ToTable("Order");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.OwnsOne("EbayPlatform.Domain.AggregateModel.MoneyValue", "Subtotal", b1 =>
                        {
                            b1.Property<long>("OrderId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Currency")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("SubtotalCurrency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)")
                                .HasColumnName("Subtotal");

                            b1.HasKey("OrderId");

                            b1.ToTable("Order");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.OwnsOne("EbayPlatform.Domain.AggregateModel.MoneyValue", "Total", b1 =>
                        {
                            b1.Property<long>("OrderId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Currency")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("TotalCurrency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)")
                                .HasColumnName("Total");

                            b1.HasKey("OrderId");

                            b1.ToTable("Order");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.OwnsOne("EbayPlatform.Domain.AggregateModel.Orders.Address", "ShippingAddress", b1 =>
                        {
                            b1.Property<long>("OrderId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("AddressID")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasComment("地址ID，同样具有唯一性，非系统ID");

                            b1.Property<string>("AddressOwner")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasComment("地址所属者");

                            b1.Property<string>("CityName")
                                .HasMaxLength(300)
                                .HasColumnType("nvarchar(300)")
                                .HasComment("城市名称");

                            b1.Property<string>("Country")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasComment("地址ID，同样具有唯一性，非系统ID");

                            b1.Property<string>("CountryName")
                                .HasMaxLength(300)
                                .HasColumnType("nvarchar(300)")
                                .HasComment("国家名称");

                            b1.Property<string>("Name")
                                .HasMaxLength(300)
                                .HasColumnType("nvarchar(300)")
                                .HasComment("地址名称");

                            b1.Property<string>("Phone")
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasComment("电话号码");

                            b1.Property<string>("PostalCode")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasComment("邮编");

                            b1.Property<string>("StateOrProvince")
                                .HasMaxLength(300)
                                .HasColumnType("nvarchar(300)")
                                .HasComment("地址ID，同样具有唯一性，非系统ID");

                            b1.Property<string>("Street")
                                .HasMaxLength(300)
                                .HasColumnType("nvarchar(300)")
                                .HasComment("街道1");

                            b1.Property<string>("Street1")
                                .HasMaxLength(300)
                                .HasColumnType("nvarchar(300)")
                                .HasComment("街道1");

                            b1.Property<string>("Street2")
                                .HasMaxLength(300)
                                .HasColumnType("nvarchar(300)")
                                .HasComment("街道2");

                            b1.HasKey("OrderId");

                            b1.ToTable("Order");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.OwnsOne("EbayPlatform.Domain.AggregateModel.Orders.CheckoutStatus", "CheckoutStatus", b1 =>
                        {
                            b1.Property<long>("OrderId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("EBayPaymentStatus")
                                .HasMaxLength(40)
                                .HasColumnType("nvarchar(40)")
                                .HasComment("EBayPaymentStatus");

                            b1.Property<bool?>("IntegratedMerchantCreditCardEnabled")
                                .HasMaxLength(10)
                                .HasColumnType("bit");

                            b1.Property<DateTime?>("LastModifiedTime")
                                .HasMaxLength(30)
                                .HasColumnType("datetime2")
                                .HasComment("最后更新时间，非系统时间");

                            b1.Property<string>("PaymentInstrument")
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)");

                            b1.Property<string>("PaymentMethod")
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasComment("结账方式");

                            b1.Property<string>("Status")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasComment("状态");

                            b1.HasKey("OrderId");

                            b1.ToTable("Order");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.OwnsMany("EbayPlatform.Domain.AggregateModel.Orders.OrderTransaction", "OrderTransactions", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasComment("主键Id")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("ConditionDisplayName")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasComment("条件性ID");

                            b1.Property<int?>("ConditionID")
                                .HasColumnType("int")
                                .HasComment("条件性ID");

                            b1.Property<DateTime?>("CreatedDate")
                                .HasColumnType("datetime2")
                                .HasComment("交易创建日期，非系统日期");

                            b1.Property<long>("OrderId")
                                .HasColumnType("bigint");

                            b1.Property<string>("OrderLineItemID")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<int>("QuantityPurchased")
                                .HasColumnType("int")
                                .HasComment("购买数");

                            b1.Property<string>("SiteCode")
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasComment("站点");

                            b1.Property<string>("Title")
                                .HasColumnType("nvarchar(max)")
                                .HasComment("标题");

                            b1.Property<string>("TransactionID")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.HasKey("Id");

                            b1.HasIndex("OrderId");

                            b1.ToTable("OrderTransaction");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");

                            b1.OwnsOne("EbayPlatform.Domain.AggregateModel.MoneyValue", "TransactionPrice", b2 =>
                                {
                                    b2.Property<long>("OrderTransactionId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("bigint")
                                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                                    b2.Property<string>("Currency")
                                        .HasMaxLength(10)
                                        .HasColumnType("nvarchar(10)")
                                        .HasColumnName("TransactionPriceCurrency");

                                    b2.Property<decimal>("Value")
                                        .HasPrecision(18, 3)
                                        .HasColumnType("decimal(18,3)")
                                        .HasColumnName("TransactionPrice");

                                    b2.HasKey("OrderTransactionId");

                                    b2.ToTable("OrderTransaction");

                                    b2.WithOwner()
                                        .HasForeignKey("OrderTransactionId");
                                });

                            b1.OwnsOne("EbayPlatform.Domain.AggregateModel.Orders.ShippingServiceOption", "ShippingServiceSelected", b2 =>
                                {
                                    b2.Property<long>("OrderTransactionId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("bigint")
                                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                                    b2.Property<bool?>("ExpeditedService")
                                        .HasColumnType("bit")
                                        .HasComment("是否加急服务");

                                    b2.Property<long>("Id")
                                        .HasColumnType("bigint");

                                    b2.Property<string>("ShippingService")
                                        .HasMaxLength(300)
                                        .HasColumnType("nvarchar(300)")
                                        .HasComment("运输服务");

                                    b2.Property<int?>("ShippingServicePriority")
                                        .HasColumnType("int");

                                    b2.Property<int?>("ShippingTimeMax")
                                        .HasColumnType("int")
                                        .HasComment("装运时间");

                                    b2.Property<int?>("ShippingTimeMin")
                                        .HasColumnType("int")
                                        .HasComment("装运时间");

                                    b2.HasKey("OrderTransactionId");

                                    b2.ToTable("OrderTransaction");

                                    b2.WithOwner()
                                        .HasForeignKey("OrderTransactionId");

                                    b2.OwnsOne("EbayPlatform.Domain.AggregateModel.MoneyValue", "ShippingServiceCost", b3 =>
                                        {
                                            b3.Property<long>("ShippingServiceOptionOrderTransactionId")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("bigint")
                                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                                            b3.Property<string>("Currency")
                                                .HasMaxLength(10)
                                                .HasColumnType("nvarchar(10)")
                                                .HasColumnName("ShippingServiceCostCurrency");

                                            b3.Property<decimal>("Value")
                                                .HasPrecision(18, 3)
                                                .HasColumnType("decimal(18,3)")
                                                .HasColumnName("ShippingServiceCost");

                                            b3.HasKey("ShippingServiceOptionOrderTransactionId");

                                            b3.ToTable("OrderTransaction");

                                            b3.WithOwner()
                                                .HasForeignKey("ShippingServiceOptionOrderTransactionId");
                                        });

                                    b2.OwnsOne("EbayPlatform.Domain.AggregateModel.Orders.ShippingPackage", "ShippingPackage", b3 =>
                                        {
                                            b3.Property<long>("ShippingServiceOptionOrderTransactionId")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("bigint")
                                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                                            b3.Property<DateTime?>("ActualDeliveryTime")
                                                .HasColumnType("datetime2");

                                            b3.Property<DateTime?>("EstimatedDeliveryTimeMax")
                                                .HasColumnType("datetime2")
                                                .HasComment("预计发货时间");

                                            b3.Property<DateTime?>("EstimatedDeliveryTimeMin")
                                                .HasColumnType("datetime2")
                                                .HasComment("预计发货时间");

                                            b3.Property<DateTime?>("ScheduledDeliveryTimeMax")
                                                .HasColumnType("datetime2");

                                            b3.Property<DateTime?>("ScheduledDeliveryTimeMin")
                                                .HasColumnType("datetime2");

                                            b3.Property<string>("ShippingTrackingEvent")
                                                .HasMaxLength(200)
                                                .HasColumnType("nvarchar(200)");

                                            b3.Property<string>("StoreID")
                                                .HasMaxLength(100)
                                                .HasColumnType("nvarchar(100)");

                                            b3.HasKey("ShippingServiceOptionOrderTransactionId");

                                            b3.ToTable("OrderTransaction");

                                            b3.WithOwner()
                                                .HasForeignKey("ShippingServiceOptionOrderTransactionId");
                                        });

                                    b2.Navigation("ShippingPackage");

                                    b2.Navigation("ShippingServiceCost");
                                });

                            b1.OwnsOne("EbayPlatform.Domain.AggregateModel.Orders.TransactionStatus", "Status", b2 =>
                                {
                                    b2.Property<long>("OrderTransactionId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("bigint")
                                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                                    b2.Property<string>("InquiryStatus")
                                        .HasMaxLength(40)
                                        .HasColumnType("nvarchar(40)")
                                        .HasComment("查询状态");

                                    b2.Property<string>("PaymentHoldStatus")
                                        .HasMaxLength(20)
                                        .HasColumnType("nvarchar(20)")
                                        .HasComment("待付款状态");

                                    b2.Property<string>("ReturnStatus")
                                        .HasMaxLength(40)
                                        .HasColumnType("nvarchar(40)")
                                        .HasComment("退回状态");

                                    b2.HasKey("OrderTransactionId");

                                    b2.ToTable("OrderTransaction");

                                    b2.WithOwner()
                                        .HasForeignKey("OrderTransactionId");
                                });

                            b1.Navigation("ShippingServiceSelected");

                            b1.Navigation("Status");

                            b1.Navigation("TransactionPrice");
                        });

                    b.OwnsOne("EbayPlatform.Domain.AggregateModel.Orders.ShippingDetail", "ShippingDetail", b1 =>
                        {
                            b1.Property<long>("OrderId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<bool?>("GetItFast")
                                .HasColumnType("bit")
                                .HasComment("是否加急");

                            b1.Property<int?>("SellingManagerSalesRecordNumber")
                                .HasColumnType("int");

                            b1.HasKey("OrderId");

                            b1.ToTable("Order");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");

                            b1.OwnsOne("EbayPlatform.Domain.AggregateModel.Orders.SalesTax", "SalesTax", b2 =>
                                {
                                    b2.Property<long>("ShippingDetailOrderId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("bigint")
                                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                                    b2.Property<float>("SalesTaxPercent")
                                        .HasColumnType("real")
                                        .HasComment("营业税率");

                                    b2.Property<string>("SalesTaxState")
                                        .HasMaxLength(300)
                                        .HasColumnType("nvarchar(300)");

                                    b2.HasKey("ShippingDetailOrderId");

                                    b2.ToTable("Order");

                                    b2.WithOwner()
                                        .HasForeignKey("ShippingDetailOrderId");

                                    b2.OwnsOne("EbayPlatform.Domain.AggregateModel.MoneyValue", "SalesTaxAmount", b3 =>
                                        {
                                            b3.Property<long>("SalesTaxShippingDetailOrderId")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("bigint")
                                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                                            b3.Property<string>("Currency")
                                                .HasMaxLength(10)
                                                .HasColumnType("nvarchar(10)")
                                                .HasColumnName("SalesTaxAmountCurrency");

                                            b3.Property<decimal>("Value")
                                                .HasPrecision(18, 3)
                                                .HasColumnType("decimal(18,3)")
                                                .HasColumnName("SalesTaxAmount");

                                            b3.HasKey("SalesTaxShippingDetailOrderId");

                                            b3.ToTable("Order");

                                            b3.WithOwner()
                                                .HasForeignKey("SalesTaxShippingDetailOrderId");
                                        });

                                    b2.Navigation("SalesTaxAmount");
                                });

                            b1.OwnsMany("EbayPlatform.Domain.AggregateModel.Orders.ShippingServiceOption", "ShippingServiceOptions", b2 =>
                                {
                                    b2.Property<long>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("bigint")
                                        .HasComment("主键Id")
                                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                                    b2.Property<bool?>("ExpeditedService")
                                        .HasColumnType("bit")
                                        .HasComment("是否加急服务");

                                    b2.Property<long>("ShippingDetailOrderId")
                                        .HasColumnType("bigint");

                                    b2.Property<string>("ShippingService")
                                        .HasMaxLength(300)
                                        .HasColumnType("nvarchar(300)")
                                        .HasComment("运输服务");

                                    b2.Property<int?>("ShippingServicePriority")
                                        .HasColumnType("int");

                                    b2.Property<int?>("ShippingTimeMax")
                                        .HasColumnType("int")
                                        .HasComment("装运时间");

                                    b2.Property<int?>("ShippingTimeMin")
                                        .HasColumnType("int")
                                        .HasComment("装运时间");

                                    b2.HasKey("Id");

                                    b2.HasIndex("ShippingDetailOrderId");

                                    b2.ToTable("Order_ShippingServiceOptions");

                                    b2.WithOwner()
                                        .HasForeignKey("ShippingDetailOrderId");

                                    b2.OwnsOne("EbayPlatform.Domain.AggregateModel.MoneyValue", "ShippingServiceCost", b3 =>
                                        {
                                            b3.Property<long>("ShippingServiceOptionId")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("bigint")
                                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                                            b3.Property<string>("Currency")
                                                .HasMaxLength(10)
                                                .HasColumnType("nvarchar(10)")
                                                .HasColumnName("ShippingServiceCostCurrency");

                                            b3.Property<decimal>("Value")
                                                .ValueGeneratedOnAdd()
                                                .HasPrecision(18, 3)
                                                .HasColumnType("decimal(18,3)")
                                                .HasDefaultValue(0m)
                                                .HasColumnName("ShippingServiceCost");

                                            b3.HasKey("ShippingServiceOptionId");

                                            b3.ToTable("Order_ShippingServiceOptions");

                                            b3.WithOwner()
                                                .HasForeignKey("ShippingServiceOptionId");
                                        });

                                    b2.OwnsOne("EbayPlatform.Domain.AggregateModel.Orders.ShippingPackage", "ShippingPackage", b3 =>
                                        {
                                            b3.Property<long>("ShippingServiceOptionId")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("bigint")
                                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                                            b3.Property<DateTime?>("ActualDeliveryTime")
                                                .HasColumnType("datetime2");

                                            b3.Property<DateTime?>("EstimatedDeliveryTimeMax")
                                                .HasColumnType("datetime2")
                                                .HasComment("预计发货时间");

                                            b3.Property<DateTime?>("EstimatedDeliveryTimeMin")
                                                .HasColumnType("datetime2")
                                                .HasComment("预计发货时间");

                                            b3.Property<DateTime?>("ScheduledDeliveryTimeMax")
                                                .HasColumnType("datetime2");

                                            b3.Property<DateTime?>("ScheduledDeliveryTimeMin")
                                                .HasColumnType("datetime2");

                                            b3.Property<string>("ShippingTrackingEvent")
                                                .HasMaxLength(200)
                                                .HasColumnType("nvarchar(200)");

                                            b3.Property<string>("StoreID")
                                                .HasMaxLength(100)
                                                .HasColumnType("nvarchar(100)");

                                            b3.HasKey("ShippingServiceOptionId");

                                            b3.ToTable("Order_ShippingServiceOptions");

                                            b3.WithOwner()
                                                .HasForeignKey("ShippingServiceOptionId");
                                        });

                                    b2.Navigation("ShippingPackage");

                                    b2.Navigation("ShippingServiceCost");
                                });

                            b1.Navigation("SalesTax");

                            b1.Navigation("ShippingServiceOptions");
                        });

                    b.OwnsOne("EbayPlatform.Domain.AggregateModel.Orders.ShippingServiceOption", "ShippingServiceSelected", b1 =>
                        {
                            b1.Property<long>("OrderId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<bool?>("ExpeditedService")
                                .HasColumnType("bit")
                                .HasComment("是否加急服务");

                            b1.Property<long>("Id")
                                .HasColumnType("bigint");

                            b1.Property<string>("ShippingService")
                                .HasMaxLength(300)
                                .HasColumnType("nvarchar(300)")
                                .HasComment("运输服务");

                            b1.Property<int?>("ShippingServicePriority")
                                .HasColumnType("int");

                            b1.Property<int?>("ShippingTimeMax")
                                .HasColumnType("int")
                                .HasComment("装运时间");

                            b1.Property<int?>("ShippingTimeMin")
                                .HasColumnType("int")
                                .HasComment("装运时间");

                            b1.HasKey("OrderId");

                            b1.ToTable("Order");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");

                            b1.OwnsOne("EbayPlatform.Domain.AggregateModel.MoneyValue", "ShippingServiceCost", b2 =>
                                {
                                    b2.Property<long>("ShippingServiceOptionOrderId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("bigint")
                                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                                    b2.Property<string>("Currency")
                                        .ValueGeneratedOnUpdateSometimes()
                                        .HasMaxLength(10)
                                        .HasColumnType("nvarchar(10)")
                                        .HasColumnName("AmountSavedCurrency");

                                    b2.Property<decimal>("Value")
                                        .HasPrecision(18, 3)
                                        .HasColumnType("decimal(18,3)")
                                        .HasColumnName("ShippingServiceCost");

                                    b2.HasKey("ShippingServiceOptionOrderId");

                                    b2.ToTable("Order");

                                    b2.WithOwner()
                                        .HasForeignKey("ShippingServiceOptionOrderId");
                                });

                            b1.OwnsOne("EbayPlatform.Domain.AggregateModel.Orders.ShippingPackage", "ShippingPackage", b2 =>
                                {
                                    b2.Property<long>("ShippingServiceOptionOrderId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("bigint")
                                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                                    b2.Property<DateTime?>("ActualDeliveryTime")
                                        .HasColumnType("datetime2");

                                    b2.Property<DateTime?>("EstimatedDeliveryTimeMax")
                                        .HasColumnType("datetime2")
                                        .HasComment("预计发货时间 Max");

                                    b2.Property<DateTime?>("EstimatedDeliveryTimeMin")
                                        .HasColumnType("datetime2")
                                        .HasComment("预计发货时间 Min");

                                    b2.Property<DateTime?>("ScheduledDeliveryTimeMax")
                                        .HasColumnType("datetime2");

                                    b2.Property<DateTime?>("ScheduledDeliveryTimeMin")
                                        .HasColumnType("datetime2");

                                    b2.Property<string>("ShippingTrackingEvent")
                                        .HasMaxLength(200)
                                        .HasColumnType("nvarchar(200)");

                                    b2.Property<string>("StoreID")
                                        .HasMaxLength(100)
                                        .HasColumnType("nvarchar(100)");

                                    b2.HasKey("ShippingServiceOptionOrderId");

                                    b2.ToTable("Order");

                                    b2.WithOwner()
                                        .HasForeignKey("ShippingServiceOptionOrderId");
                                });

                            b1.Navigation("ShippingPackage");

                            b1.Navigation("ShippingServiceCost");
                        });

                    b.Navigation("AdjustmentAmount");

                    b.Navigation("AmountPaid");

                    b.Navigation("AmountSaved");

                    b.Navigation("CheckoutStatus");

                    b.Navigation("OrderTransactions");

                    b.Navigation("ShippingAddress");

                    b.Navigation("ShippingDetail");

                    b.Navigation("ShippingServiceSelected");

                    b.Navigation("Subtotal");

                    b.Navigation("Total");
                });

            modelBuilder.Entity("EbayPlatform.Domain.AggregateModel.SyncTaskJobConfig", b =>
                {
                    b.OwnsMany("EbayPlatform.Domain.AggregateModel.ShopTask", "ShopTasks", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("ParamValue")
                                .HasMaxLength(4000)
                                .HasColumnType("nvarchar(4000)")
                                .HasComment("参数值");

                            b1.Property<string>("ShopName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasComment("店铺名称");

                            b1.Property<int>("ShopTaskStatus")
                                .HasColumnType("int");

                            b1.Property<int>("SyncTaskJobConfigId")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("SyncTaskJobConfigId");

                            b1.ToTable("ShopTask");

                            b1.WithOwner()
                                .HasForeignKey("SyncTaskJobConfigId");
                        });

                    b.Navigation("ShopTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
