// <auto-generated />
using System;
using EbayPlatform.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EbayPlatform.Infrastructure.Migrations
{
    [DbContext(typeof(EbayPlatformDbContext))]
    [Migration("20210827084045_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EbayPlatform.Domain.Models.SyncTaskJobConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("主键Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasComment("创建日期");

                    b.Property<string>("Cron")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Cron");

                    b.Property<string>("CronDesc")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasComment("Cron描述");

                    b.Property<bool>("IsRunning")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("是否运行中");

                    b.Property<string>("JobClassFullName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasComment("Jo类全名");

                    b.Property<string>("JobDesc")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Job描述");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Job名称");

                    b.Property<int>("JobStatus")
                        .HasColumnType("int")
                        .HasComment("运行状态");

                    b.Property<DateTime?>("ModifyDate")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2")
                        .HasComment("更新日期");

                    b.HasKey("Id");

                    b.ToTable("SyncTaskJobConfig");

                    b
                        .HasComment("同步任务作业配置表");
                });

            modelBuilder.Entity("EbayPlatform.Domain.Models.SystemLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("主键Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasComment("内容");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasComment("创建日期");

                    b.Property<int>("LogType")
                        .HasColumnType("int")
                        .HasComment("日志类型");

                    b.Property<int>("ObjectId")
                        .HasColumnType("int")
                        .HasComment("外键Id");

                    b.HasKey("Id");

                    b.ToTable("SystemLog");

                    b
                        .HasComment("系统日志表");
                });

            modelBuilder.Entity("EbayPlatform.Domain.Models.SyncTaskJobConfig", b =>
                {
                    b.OwnsMany("EbayPlatform.Domain.Models.SyncTaskJobParam", "SyncTaskJobParams", b1 =>
                        {
                            b1.Property<int>("SyncTaskJobConfigId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("ParamValue")
                                .HasColumnType("nvarchar(max)")
                                .HasComment("参数值");

                            b1.Property<string>("ShopName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasComment("店铺名称");

                            b1.HasKey("SyncTaskJobConfigId", "Id");

                            b1.ToTable("SyncTaskJobParam");

                            b1.WithOwner()
                                .HasForeignKey("SyncTaskJobConfigId");
                        });

                    b.Navigation("SyncTaskJobParams");
                });
#pragma warning restore 612, 618
        }
    }
}
